### ISSUE TITLE
None of the Korthia Rift Caches actually show up

### ISSUE THREAD

**Issue by entropy1997** [zarillion/handynotes-plugins#122]
I went into the rift portal in search of the Rift Caches, however, all the caches that was shown by handynotes weren't physically there. I came to each location and there was nothing. Please troubleshoot.

**Comment by zarillion** [comment]
I have not personally experienced this outside of the "Rift Hidden Caches" in the maw, which turned out to be tied to the Night Fae assault. The newest release now only shows those inside the rift when that assault is active. The "Riftbound Caches" in Korthia should always be there inside the rift, but may be missing if someone recently looted them. In that case you would have to check again later.

If you continue to have issues, please screenshot the exact chest locations and attach them here.
