### ISSUE TITLE
Ve'nari - Broker Traversal Enhancer incorrectly marked as Incomplete

### ISSUE THREAD

**Issue by Dranni21312** [zarillion/handynotes-plugins#133]
With the item purchased and consumed, handynotes is reporting that this item is still missing. See below:

![image](https://user-images.githubusercontent.com/80227585/127628164-f5b429b9-190c-4758-8c1c-a342afb51f50.png)

![image](https://user-images.githubusercontent.com/80227585/127628193-cc4c741a-cce3-4538-a171-3db09428301a.png)

![image](https://user-images.githubusercontent.com/80227585/127628247-2082b45a-3d0f-41ae-981f-f8df1df8f5d4.png)

**Comment by Dathwada** [comment]
Could you please check if you have bought this on an alt?

**Comment by Dranni21312** [comment]
Yes, it looks like I have purchased it on one of my alts. I cannot obtain it on my main though because it's a once-per-account deal. How to make handynotes aware of this?

**Comment by Dathwada** [comment]
For now we don't have a solution. We are tracking these items with hidden quest ids but unfortunately they are only on the char you have redeemed this item "true" for the other chars they are "false".

**Comment by zarillion** [comment]
As @Dathwada says, we do not have a good solution for this at this time, which is why we include the note on Ve'nari:

![image](https://user-images.githubusercontent.com/64381982/127749994-bf8282eb-0f04-4745-886d-a41b9092890e.png)

If we can find a way to query the status of Torghast upgrades that does not rely on these quest ids, we can fix this later.
