### ISSUE TITLE
Trivial location correction on a HN:DF item

### ISSUE THREAD

**Issue by SoulCookie** [zarillion/handynotes-plugins#238]
**Very** minor location correction on a "Fragments of History" lootable item:

**Wrapped Gold Band** is labeled as being under the dragon statue's _right_ rear leg, but I instead found it under under the statue's _**left**_ rear leg. 

Azure Span / Cobalt Assembly, 46, 25ish. Here is _(I think)_ the tracking quest that popped when I looted the band: 
`[46202403] = {quest=70297, label=""},`

Thanks for all the work you do on these!

**Comment by Dathwada** [comment]
Yes you're right the wrapped gold band is under the dragon statue's left rear leg. This will be fixed in the next release.
And I guess your profession is Inscription, because the quest id `70297` belongs to Dusty Darkmoon Card (Profession Knowledge treasure)
![grafik](https://user-images.githubusercontent.com/57680823/206217166-73c90d8b-6719-4a57-949a-d42fb1e4592a.png)

**Comment by Krovikan** [comment]
Thanks @SoulCookie . Changed for the next release.

https://github.com/zarillion/handynotes-plugins/commit/5108d50575e773c8a4a1308bbdaa6da2706b98fc
