### ISSUE TITLE
Addon keeps showing the Rares icon on map after kill them. v1.2

### ISSUE THREAD

**Issue by Galthariel** [zarillion/handynotes-plugins#28]
I'm in Icecrown in after last update the icons are still showing all the rares regardless if they were killed by me or not and "Show Completed" is unchecked

**Comment by zarillion** [comment]
That change is intentional. The quest ids for each boss resets when the next one spawns. You can loot them as many times as you want.

Hiding the boss based on quest id would only hide the boss for 20 minutes, then the icon would reappear. Instead we opted to just show them always and add a note indicating they can be looted over and over again.

**Comment by Galthariel** [comment]
I did not knew I can loot them many times. Usually rares can be looted once a day. Tks
