### ISSUE TITLE
HUGE FPS drop after viewing rare icons on the icecrown map

### ISSUE THREAD

**Issue by n47h4ni3l** [zarillion/handynotes-plugins#29]
Everytime I hover over an icon on the icecrown map my FPS drops from 70fps to around 7 making the game unplayable. /reload fixes it until I look at the map again but this is annoying to do everytime I want to check rare spawn pathing.

**Comment by KnewOne** [comment]
This is inded an issue and it's one caused by this addon using wrong approach to texturing paths and icons. [MBB](https://www.curseforge.com/wow/addons/mbb) uses the textures given by the mod and for some reason recognises them as minimap buttons for addons loading their textures as a unit.
![image](https://user-images.githubusercontent.com/41551327/98806893-8abc0d00-2422-11eb-8aed-41527ce35e29.png)
This is the MBB itself with 2 correct addon buttons being details and tsm and the textures of this addon.
![image](https://user-images.githubusercontent.com/41551327/98806999-ae7f5300-2422-11eb-84af-21dfb6491c59.png)
This is a listing of textures, which the addon sees as buttons. 
Is there any chance you will change the way it works for future versions of addons ? This isn't an issue with the other handynotes addons.

I'll link my MBB issue here aswell for future reference https://github.com/vallantv/MBB/issues/13

**Comment by dmartinzar** [comment]
My HandyNotes plugins are unique regarding those points of interest and paths. To support drawing paths, points of interest, lines, arrows and icon glows (see [Mystic Rainbowhorn](https://shadowlands.wowhead.com/npc=164547/mystic-rainbowhorn) in Ardenweald) the plugin registers new world map and minimap providers configured to display icons *underneath* the layer that standard HandyNotes icons appear at.

For the minimap, it uses the same HereBeDragons library calls to add the minimap icons as HandyNotes itself, yet the standard HandyNotes icons are not picked up by MBB as buttons to display. I'll look at the plugin to see if there is some special attributes I can set on the provider or icons to tell it to ignore them. @n47h4ni3l are you also using this MBB addon?

**Comment by n47h4ni3l** [comment]
I can confirm that MBB is definitely the conflict by the process of elimination. @IKnewOne's info is spot on.

**Comment by NHDriver4** [comment]
Just wanted to stop by and say I was experiencing the same lag and also running MBB. Disabling MBB resolved the lag issue. Just wanted to confirm the conflict. Thanks for your work on this!

**Comment by zarillion** [comment]
My HandyNotes plugins are unique regarding those points of interest and paths. To support drawing paths, points of interest, lines, arrows and icon glows (see [Mystic Rainbowhorn](https://shadowlands.wowhead.com/npc=164547/mystic-rainbowhorn) in Ardenweald) the plugin registers new world map and minimap providers configured to display icons *underneath* the layer that standard HandyNotes icons appear at.

For the minimap, it uses the same HereBeDragons library calls to add the minimap icons as HandyNotes itself, yet the standard HandyNotes icons are not picked up by MBB as buttons to display. I'll look at the plugin to see if there is some special attributes I can set on the provider or icons to tell it to ignore them.

*Edit: reposting under correct account =)*

**Comment by zarillion** [comment]
The method MBB uses to figure out which minimap frames are buttons and which are icons to ignore is inherently unsustainable:

https://github.com/vallantv/MBB/blob/master/MBB.lua#L59

The author attempts to maintain a list of all addon frames and pin types that his addon should ignore. *Any* addon that registers a provider and creates frames with names not in that list will cause issues. To fix this issue he would need to ignore `HandyNotes*Pins` instead of just `HandyNotesPins`, and add the necessary code to support those types of pattern matches. That would fix it for my plugins until the next random addon comes along that breaks his code ...

**Comment by zarillion** [comment]
Closing as there's nothing to do on my end.
