### ISSUE TITLE
Known toys not set as completed

### ISSUE THREAD

**Issue by Arxareon** [zarillion/handynotes-plugins#305]
**ADDON VERSION**: 32

**Describe the bug**
Know toy-only treasures are not filtered as completed automatically. I don't know it it's all known toys or just a couple ones. See the image below as an example.

**Screenshots**
![image](https://user-images.githubusercontent.com/33066061/224225396-69bb6eab-5479-4685-b347-3155304b08e2.png)
*Notice that "Show completed" is off.*

**Comment by ghost** [comment]
@Arxareon That node is a "treasure" node and not a "rare" node so I don't believe the "Hide rare if all rewards known" would affect it.

However, from the looks of your screenshot you must have collected the toy on another character but not collected the treasure on this current character because the achievement criteria (the gray "Lost Compass") isn't green. "Treasure" nodes only hide when all rewards (in this case the achievement criteria and the toy) are known.

You can hide the node manually if you want by right clicking on it. Hopefully that makes sense!

**Comment by Arxareon** [comment]
I see. I wasn't expecting the rares option would hide it but having show completed would.
But, if I understand correctly, it shown because of the achi, not the toy. In which case, an option to filter out the whole achi would be nice but it's not a bug then.
I'll filter them manually for now, thanks! 😁
