### ISSUE TITLE
Zaralek: no info about rare spawn rotation

### ISSUE THREAD

**Issue by Danielosama** [zarillion/handynotes-plugins#367]
**ADDON VERSION**: **v42**

**Describe the bug**

Handynotes does not show anymore which rare can spawn or not in Zaralek cavern (rotation).

Installing v41 solves the issue.

**Comment by Krovikan** [comment]
Hello @Danielosama 

Sorry but is a feature removed intentionally as the changelog says:

-     Added Dreamsurge rewards.
-     Added Elusive Skinning Bait creatures.
-     Added pet battles for the Battle on the Dragon Isles II achievement.
-     Added rewards from the Fyrakk Assault.
-     Added Secrets of Azeroth nodes across the world for all 15 secrets!
-     Added some prep-work for future Dragonracing cups.
-     Added The Gift of Cheese achievement.
-     Added the Many Boxes, Many Rockses achievement.
-     Added the Revival Catalyst.
-     Fixed a conflict with RareScanner tooltips.
-     **Removed some spawn info that wasn't always correct.**
-     Updated some Kalimdor Cup values.

We prefer don't show info instead of inaccurate info.

Greetings
