### ISSUE TITLE
Most items classified as "Unobtainable" in the Dragon Isles are now obtainable regardless of your class

### ISSUE THREAD

**Issue by jungheeMW** [zarillion/handynotes-plugins#428]
**ADDON VERSION**: (place version of the addon you have installed here)
Dragonflight v63

**Describe the bug**
Not sure if this change happened after the introduction of warband transmog collecting, but many rares in the Dragon Isles can now drop gear that your class cannot equip, allowing you to collect their appearance for your account/warband. The tooltip however, still uses the term "Unobtainable". I cannot confirm if this is true for all Dragon Isles rares or just the ones in Zaralek Caverns.

This also has the additional effect of hiding a rare's skull from the map when you have only collected the appearances your class can use. If the rare has additional unlearned appearances that you class cannot use, it will be hidden if the option "Hide rare if all rewards known" is checked.

As an example, my demon hunter was able to get [Subterrax's Stout Waistguard](https://www.wowhead.com/item=205312/subterraxs-stout-waistguard) and [Magmascale Pauldrons](https://www.wowhead.com/item=205311/magmascale-pauldrons) to drop, despite both of these items being mail and not leather.
I also attached a screenshot of what the tooltip currently looks like.

**Screenshots**
<img width="263" alt="handynotes zarillion" src="https://github.com/user-attachments/assets/aeb36c30-d0b2-4a4b-8a7a-25b2390d8b30">

**Comment by zarillion** [comment]
Going to close this for now. We investigated this bit and have decided to keep trusting the table of specs a piece can drop for because it still seems to be correct _most of the time_. If this causes problems we can re-evaluate.

I would rather something say it is unobtainable but actually can drop than have it say it _can_ drop and waste someones time farming a piece their class cannot obtain, if that makes sense.
