### ISSUE TITLE
[flaw] No loot info when rare has already spawned (ICC rares)

### ISSUE THREAD

**Issue by tflo** [zarillion/handynotes-plugins#48]
Often I’m late to log-in to my parked toon – and sometimes I log in to the wrong toon (the leather toon instead of the plate toon, e.g.).

Unfortunately, when the rare is already up, there is no way to check the loot (in order to determine if I’m on the right toon), since the loot display vanishes once a rare is up.

I would love to be able to see the loot of the rare also when he is already up. (We still have 2 minutes then.)

Not sure, if this is clear. Let me know, if more explanations are needed. And let me know if I’m missing something.

**Comment by zarillion** [comment]
This has to do with the UI ordering of the icons. When the Blizzard vignette skull appears, it is drawn *above* the layer that HandyNotes puts its icons in. I do not have control over this from the plugin, so the Blizzard skull blocks out the plugin's skull and the tooltip does not appear on mouseover.

However, the minimap works the opposite. Unlike the world map, the minimap does not have a layering system. All addon pins are drawn *above* any Blizzard icons, so our plugin skull should appear above the Blizzard vignette skull. If you hover over the icon on the minimap you should see the tooltip.

I'm going to close this issue since it is ICC related. All prepatch code will be deleted in 5 days when SL launches, so I'm locking the code for it and not making any changes until then.

**Comment by tflo** [comment]
Thanks for the detailed explanation. It didn’t occur to me that this could be the Blizz vignette hiding your icon. 

Good to know, also for future similar issues with other add-ons or other HN plugins. Also thanks for the Minimap tip.

Of course, it is OK to close this. Thanks!
