### ISSUE TITLE
Weapon types show as "unobtainable" appearances for warriors on tooltips that are actually obtainable

### ISSUE THREAD

**Issue by TheCheat54** [zarillion/handynotes-plugins#52]
So when you mouse over the tooltip for a rare that has a chance to drop a weapon which doesn't have primary stat as strength, HandyNotes: Shadowlands is for whatever reason telling warriors they cannot obtain the appearance. This is patently false. Warriors can equip every weapon type in the game except wands and warglaives, and these items in SL do so far appear to be able to drop even if I otherwise can't get use out of them.

**Comment by zarillion** [comment]
The `Unobtainable` status indicates the item does not drop for you, but if someone traded you the item you could learn the appearance. It is driven off the [GetItemSpecInfo](https://wow.gamepedia.com/API_GetItemSpecInfo) function, which returns a table of class specializations the item will drop for.

If the item says `Unobtainable` for you, that means the `GetItemSpecInfo()` function returned an empty table, indicating your class did not have any specs it would drop for. If this is not accurate for a given item and it does indeed directly drop for you, that would be a bug in the `GetItemSpecInfo()` function and nothing this addon could fix on its own.

**Comment by TheCheat54** [comment]
To me, this seems like a case where functionality could be enhanced by taking an entirely different path. GetItemSpecInfo seems clearly intended to only care about drops where loot spec actually matters (i.e. dungeon/raid, PvP content) and simply isn't as helpful for rares where all items can drop for everyone. Mapping a matrix of what classes can learn what weapons and their armor type, checking the player's class to see if valid, and then checking the item's collected status if obtainable would be possible with other functions.

It probably qualifies as an enhancement request in that regard but the point remains.

**Comment by zarillion** [comment]
You say loot spec only matters in instanced content, but that's actually not the case. In Mechagon, all of the rares only dropped items appropriate for your loot spec, which is where this code was added. I'm speaking from experience of my own wasted time, I tried to get the [1H STR Sword](https://www.wowhead.com/item=170467/whirring-chainblade?bonus=4802) appearance from Gear Checker Cogstar for weeks on my warlock before I realized it obeyed spec restrictions and literally could not drop for me.

I would rather have the addon be overly cautious than risk wasting peoples time like I did. I don't want to tell them an appearance drops that they technically can learn but it turns out it will never drop for them. It would be great if there was a way in the API to determine whether a rare is a Mechagon-type that obeys `GetItemSpecInfo()` or a free-for-all loot style rare.

**Comment by TheCheat54** [comment]
That's a completely valid concern and I get it. I can confirm for you directly however that the rares in Shadowlands are dropping their stuff for everyone regardless of spec. I loot non-plate armor all the time from them in addition to having some of the weapon mogs (e.g. the intellect scythe-staves from Ardenweald).
