### ISSUE TITLE
Treasure still shown after getting the achievement

### ISSUE THREAD

**Issue by Tasmanien** [zarillion/handynotes-plugins#55]
Hi,
I got the "Treasures of Ardenwaeld" on my main.
When I check the map on my alt, I still see treasures even if the tooltip shows everything as completed.
Is there an issue with account achievements?

![image](https://user-images.githubusercontent.com/6470492/100600645-d6672580-3301-11eb-9ee2-bcf2ae5fffb8.png)

Thanks :)

**Comment by Dathwada** [comment]
Hi, make sure you have "Show completed" disabled via the dropdown menu at the top right of your world map (treasure icon).

![ss+(2020-11-30+at+03 49 45)](https://user-images.githubusercontent.com/57680823/100625013-556d5580-3324-11eb-982a-036840207bd9.jpg)

**Comment by zarillion** [comment]
The treasures still showing up is by design. Historically, the treasure icons in most HandyNotes plugins are per-character, so even if you have the rewards and achievement credit the treasure will appear on the map as long as the quest ID associated with it is `false` for that character.

This plugin supports many other types of "collectible" nodes that do not necessarily have quests associated with them. These types of nodes are hidden for all characters once the achievement criteria and rewards have been collected. I have not considered converting the standard treasure nodes to this type, but maybe a discussion is warranted for it.

**Comment by adavak** [comment]
the rares are daily. even you killed and the next day you can loot again for anima.
so, our mission is change all blue skull to white.

is different before bfa and legion.
